import framesJson from './frames.json'
import type { GlassesFit } from '@/vto/lib/glbAnalyzer'

/** A single catalog frame. Shape matches `frames.json` (Story 06 AC4). */
export interface FrameAttribution {
  creator: string
  license: string
  sourceUrl: string
}

export interface Frame {
  id: string
  name: string
  modelUrl: string
  thumbUrl: string
  attribution: FrameAttribution
  /**
   * Per-model registration/occlusion params for USER-UPLOADED frames, derived
   * by glbAnalyzer at upload time. Absent on shipped catalog frames (they are
   * authored to the canonical conventions — GlassesSwap falls back to
   * DEFAULT_FIT).
   */
  fit?: GlassesFit
  /** True for user-uploaded frames (stored in IndexedDB, deletable). */
  custom?: boolean
}

/**
 * The glasses catalog, loaded synchronously as a bundled JSON import (AC10:
 * "Catalog is preloaded as JSON on app start"). The GLBs themselves lazy-load
 * via `useGLTF` only when a frame is selected.
 *
 * Generated by `app/scripts/generate-catalog.mjs` — do not hand-edit; rerun the
 * generator to change the catalog.
 */
export const FRAMES: readonly Frame[] = framesJson as Frame[]

/** The id selected on first paint. */
export const DEFAULT_FRAME_ID: string = FRAMES[0]?.id ?? ''
