/**
 * Lens tints for the sunglasses try-on.
 *
 * Unlike `frames.json` (generated by `scripts/generate-catalog.mjs` — do not
 * hand-edit), tints are a small HAND-AUTHORED palette applied to the live model
 * at runtime. The deployed `sunglasses.glb` ships one baked, near-opaque lens;
 * selecting a tint here recolors that lens and makes it see-through so the
 * wearer's eyes show through (GlassesSwap reads `selectedTint` and writes the
 * values below onto the `lens_*` materials each time the selection changes).
 *
 * `lensOpacity` is the per-material BASE opacity (0..1) the face-presence /
 * cross-fade system multiplies into the final alpha — lower = darker/less of the
 * eyes visible. `metalness`/`roughness` are optional overrides; leave metalness
 * at 0 for a flat tinted glass, raise it for a reflective "mirror" look.
 */
export interface Tint {
  id: string
  name: string
  /** Lens base colour, `#rrggbb`. Also used as the swatch fill in the panel. */
  colorHex: string
  /** Base opacity 0..1 (~0.5 = a hint of the eyes). */
  lensOpacity: number
  /** Optional reflectivity override (default 0 = flat tint). */
  metalness?: number
  /** Optional roughness override (default left to the recipe in GlassesSwap). */
  roughness?: number
  /** Optional HDRI reflection strength (default 1). Lower tames mirror blowout. */
  envMapIntensity?: number
}

/**
 * "Classic 6" everyday palette. Starting values — tune live against the webcam.
 * Smoke is the default (a neutral medium tint that reveals a hint of the eyes).
 */
export const TINTS: readonly Tint[] = [
  // Opacity bumped up a notch (less see-through) with a touch of reflectivity
  // (envMapIntensity > default 1) so the HDRI reads on the lens.
  { id: 'smoke', name: 'Smoke', colorHex: '#3a3a3e', lensOpacity: 0.72, envMapIntensity: 1.3 },
  { id: 'brown', name: 'Brown', colorHex: '#5a3a1e', lensOpacity: 0.72, envMapIntensity: 1.3 },
  { id: 'green', name: 'G-15 Green', colorHex: '#2f3b2f', lensOpacity: 0.72, envMapIntensity: 1.3 },
  { id: 'blue', name: 'Blue', colorHex: '#2a3550', lensOpacity: 0.72, envMapIntensity: 1.3 },
  { id: 'rose', name: 'Rose', colorHex: '#5a2f3a', lensOpacity: 0.76, envMapIntensity: 1.3 },
  {
    id: 'silver',
    name: 'Silver Mirror',
    colorHex: '#9aa0a6',
    lensOpacity: 0.72,
    metalness: 0.6,
    roughness: 0.25,
    // Reflective, but dial the HDRI down so the specular doesn't blow out over
    // the eyes. Tune live in the Phase-0 triage.
    envMapIntensity: 0.8,
  },
]

/** The tint applied on first paint. */
export const DEFAULT_TINT_ID = 'smoke'
